voice: ash
instructions: |
  Gyerekeknek olvasol mesét. Nyugodt, lassú, meleg hangon beszélj. Ne siess, tagoltan beszélj, és nyugodtan.
story: |
  Boribon és Annipanni elmentek szőlőt szedni. Letépték a szőlőt, és hazamentek a kosarukkal. Megették, kakiltak és fürödni mentek, megmosták a fogukat, majd lefeküdtek az ágyba. Boribon már horkol, Annipanni, te is aludj légyszíves! Jaj, itt egy bogár, hú de csípős! Úgy hívják, hogy szúnyog! Jaj, megcsípett, hú de fáj! Hívjuk az orvost! Jaj, nem jön az orvos! Lehet, hogy horkol ő is! Vagy lehet, hogy ő is megbetegedett? Fúj, a hangszórót kezdte összeszurkálni a szúnyog!
